// The sampled half of the bank: which families exist, and how loud each is.
//
// GAIN IS CALIBRATED, NOT CHOSEN. A first pass measured a 100x spread across
// the bank — violin at rms 0.004 against the 808 at 0.44 — which the app would
// have played as "some of these instruments are broken" the moment a song
// picked four of them at once. tools/bank-audition.mjs renders every voice
// playing the same motif and reports what each needs to reach the bank median;
// these are those numbers. Re-run it whenever the bank changes.
//
// Sources and licences are in assets/samples/PROVENANCE.md, generated by
// tools/build-samples.mjs from tools/samples-manifest.json. Everything is CC0.
export const SAMPLE_GAIN = {
  piano: 0.58,
  guitar: 1.10,     // acoustic archtop
  eguitar: 1.62,    // clean electric
  violin: 8.55,     // quietest source in the bank by a wide margin
  flute: 2.26,
};

// A sampled voice spec. `cutoff` sits above hearing because a recording
// carries its own spectrum — the brightness envelope that helps a synthesised
// voice is a no-op here (only 0.5-2.1% of a real instrument's energy sits
// above 4.2kHz, measured in v3.67), so sampled voices never get `open`.
export function sampleVoice(family, buffer, rootFreq) {
  return {
    name: family, kind: 'sample', buffer, rootFreq,
    cutoff: 20000, atk: 0.003, dec: 0, decRel: 0,
    gain: SAMPLE_GAIN[family] ?? 1,
  };
}

// Distortion is a nonlinearity applied to a clean signal, so the distorted
// electric guitar is the clean recording through a waveshaper rather than a
// second set of samples. Rock is 18.6% of US streams and 21% of all hits carry
// distorted guitar (INSTRUMENT-BANK.md) — worth having, not worth 0.3MB.
export function distorted(voice, drive = 3.2) {
  return { ...voice, name: voice.name + '-dist', drive, gain: (voice.gain ?? 1) * 0.45 };
}
